approved = [
    "mit",
    "apache-2.0",
    "bsd-3-clause",
    "bsd-2-clause",
    "mpl-2.0",
]

ignored = [
    "github.com/ghodss/yaml",
    "github.com/davecgh/go-spew", # ISC license
    "github.com/gogo/protobuf", # BSD
    "gomodules.xyz/jsonpatch/v2",
    "gopkg.in/fsnotify.v1",

    # Vanity URLS :\
    "google.golang.org/grpc",
    "google.golang.org/genproto",
    "sigs.k8s.io/yaml",
]