# Default values for hollowtrees-with-ps
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: banzaicloud/hollowtrees
  tag: "0.1.1"
  imagePullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

log:
  format: logfmt
  level: debug

healthcheck:
  listenPort: 8082
  endpoint: /healthz

promalert:
  listenPort: 8080
  useJWTAuth: false

scaler:
  name: pipeline-scaler
  description: Pipeline cluster scaling
  hostname: localhost
  port: 9993
  type: grpc
  allowedEvents:
  - prometheus.server.alert.InstanceTermination
  groupBy:
  - org_id
  - cluster_id
  - cluster_name
  - instance_id
  cooldown: 5m

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - "/hollowtrees-alerts"

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    memory: 256Mi
    cpu: 120m

htpsp:
  listenPort: 9993
  image:
    repository: banzaicloud/ht-pipeline-scaler-plugin
    tag: "0.1.0"
    imagePullPolicy: IfNotPresent
  log:
    format: logfmt
    level: debug
  healthcheck:
    listenPort: 8083
    endpoint: /healthz
  scaler:
    pipeline:
      url: 
      skipTLSVerify: false
    telescopes:
      url: 
      skipTLSVerify: false
    retries: 2
    waitBetweenRetries: 10s
    waitInQueue: 60s
  resources:
    requests:
      memory: 256Mi
      cpu: 120m

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
