apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hollowtrees-with-ps.fullname" . }}
  labels:
{{ include "hollowtrees-with-ps.labels" . | indent 4 }}
data:
  config.yaml: |-
    log:
      format: {{ .Values.log.format | quote }}
      level: {{ .Values.log.level | quote }}

    healthcheck:
      listenAddress: ":{{ .Values.healthcheck.listenPort }}"
      endpoint: {{ .Values.healthcheck.endpoint | quote }}

    promalert:
      listenAddress: ":{{ .Values.promalert.listenPort }}"
      useJWTAuth: {{ .Values.promalert.useJWTAuth }}

    plugins:
    - name: {{ .Values.scaler.name | quote }}
      address: "{{ .Values.scaler.hostname }}:{{ .Values.scaler.port }}"
      type: {{ .Values.scaler.type | quote }}

    flows:
      scaler:
        name: {{ .Values.scaler.name | quote }}
        description: {{ .Values.scaler.description | quote }}
        allowedEvents:
        {{- range .Values.scaler.allowedEvents }}
        - {{ . | quote }}
        {{- end }}
        plugins:
        - {{ .Values.scaler.name | quote }}
        cooldown: {{ .Values.scaler.cooldown | quote }}
        groupBy:
        {{- range .Values.scaler.groupBy }}
        - {{ . | quote }}
        {{- end }}
