{{- if .Values.promalert.useJWTAuth -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "hollowtrees-with-ps.fullname" . }}
  labels:
{{ include "hollowtrees-with-ps.labels" . | indent 4 }}
type: Opaque
data:
  tokenSigningKey: {{ required "tokenSigningKey must be defined if JWT auth is enabled" .Values.promalert.jwtSigningKey | b64enc | quote }}
{{- end }}
